const SUPABASE_URL='https://lodrmcojkxedwsmkinyj.supabase.co';
const SUPABASE_KEY='sb_publishable_tlT9YGMMLBndjqguXwC-3A_lBZR0GKn';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentRoom=null,roomChannel=null,isHost=false; const $=id=>document.getElementById(id);
const createTab=$('createTab'),joinTab=$('joinTab'),createView=$('createView'),joinView=$('joinView'),lobbyPanel=$('lobbyPanel'),roomPanel=$('roomPanel'),statusText=$('statusText');
function setTab(mode){const c=mode==='create';createTab.classList.toggle('active',c);joinTab.classList.toggle('active',!c);createView.classList.toggle('hidden',!c);joinView.classList.toggle('hidden',c);statusText.textContent=''} createTab.onclick=()=>setTab('create');joinTab.onclick=()=>setTab('join');
function makeCode(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:4},()=>c[Math.floor(Math.random()*c.length)]).join('')}
async function createRoom(){const b=$('createRoomBtn');b.disabled=true;statusText.textContent='Creating your room...';try{let row=null,a=0;while(!row&&a++<5){const {data,error}=await db.from('arcade_rooms').insert({room_code:makeCode(),host_name:$('hostName').value.trim()||'Baby',status:'waiting'}).select().single();if(!error)row=data;else if(error.code!=='23505')throw error}if(!row)throw Error();isHost=true;enterRoom(row)}catch(e){console.error(e);statusText.textContent='Could not create room. Try again ❤️'}finally{b.disabled=false}}
async function joinRoom(){const b=$('joinRoomBtn'),code=$('roomCodeInput').value.trim().toUpperCase(),name=$('guestName').value.trim()||'Sayang';if(!code){statusText.textContent='Enter the room code dulu 💗';return}b.disabled=true;try{const {data:r,error}=await db.from('arcade_rooms').select('*').eq('room_code',code).maybeSingle();if(error)throw error;if(!r){statusText.textContent='Room tak jumpa 🥺';return}if(r.guest_name){statusText.textContent='Room ni dah ada dua player ❤️';return}const {data:u,error:x}=await db.from('arcade_rooms').update({guest_name:name,status:'ready'}).eq('id',r.id).is('guest_name',null).select().maybeSingle();if(x)throw x;if(!u){statusText.textContent='Someone joined first 🥺';return}isHost=false;enterRoom(u)}catch(e){console.error(e);statusText.textContent='Could not join room ❤️'}finally{b.disabled=false}}
function renderRoom(r){currentRoom=r;$('roomCodeLabel').textContent=r.room_code;$('hostLabel').textContent=r.host_name||'Baby';$('guestLabel').textContent=r.guest_name||'Waiting...';const c=!!r.guest_name;$('connectionState').textContent=c?'Both players are connected ❤️':'Waiting for your person to join...';$('connectionState').classList.toggle('ready',c);document.querySelector('[data-game="card-battle"]').disabled=!c;document.querySelector('[data-game="love-pong"]').disabled=!c;if(r.selected_game==='card-battle'&&r.game_state?.phase==='battle')showBattle(r);if(r.selected_game==='love-pong'&&r.game_state?.phase==='pong')showLovePong(r)}
function enterRoom(r){statusText.textContent='';lobbyPanel.classList.add('hidden');roomPanel.classList.remove('hidden');renderRoom(r);subscribeRoom(r.id)}
function subscribeRoom(id){if(roomChannel)db.removeChannel(roomChannel);roomChannel=db.channel(`arcade-room-${id}-${Math.random().toString(36).slice(2)}`).on('postgres_changes',{event:'*',schema:'public',table:'arcade_rooms',filter:`id=eq.${id}`},async p=>{if(p.eventType==='DELETE'){resetToLobby('Room closed.');return}if(p.new?.id)renderRoom(p.new)}).subscribe(async status=>{if(status==='SUBSCRIBED'){const {data}=await db.from('arcade_rooms').select('*').eq('id',id).maybeSingle();if(data)renderRoom(data)}})}
async function leaveRoom(){if(!currentRoom){resetToLobby();return}try{if(isHost)await db.from('arcade_rooms').delete().eq('id',currentRoom.id);else await db.from('arcade_rooms').update({guest_name:null,status:'waiting',selected_game:null,game_state:{}}).eq('id',currentRoom.id)}catch(e){console.error(e)}resetToLobby()}
function resetToLobby(m=''){if(roomChannel){db.removeChannel(roomChannel);roomChannel=null}if(pongLoop){clearInterval(pongLoop);pongLoop=null}currentRoom=null;isHost=false;$('battlePanel').classList.add('hidden');$('pongPanel').classList.add('hidden');roomPanel.classList.add('hidden');lobbyPanel.classList.remove('hidden');statusText.textContent=m}
$('createRoomBtn').onclick=createRoom;$('joinRoomBtn').onclick=joinRoom;$('roomCodeInput').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''));$('copyCodeBtn').onclick=async()=>{if(!currentRoom)return;try{await navigator.clipboard.writeText(currentRoom.room_code);$('copyCodeBtn').textContent='Copied ❤️';setTimeout(()=>$('copyCodeBtn').textContent='Copy room code',1400)}catch{alert(`Room code: ${currentRoom.room_code}`)}};$('leaveRoomBtn').onclick=leaveRoom;
document.querySelector('[data-game="card-battle"]').onclick=startCardBattle;$('rematchBtn').onclick=startCardBattle;$('backBattleBtn').onclick=exitBattle;
document.querySelector('[data-game="love-pong"]').onclick=startLovePong;$('pongRematchBtn').onclick=rematchLovePong;$('backPongBtn').onclick=exitLovePong;
window.addEventListener('beforeunload',()=>{if(roomChannel)db.removeChannel(roomChannel);if(pongLoop)clearInterval(pongLoop)});