const LOVE_QUIZ_QUESTIONS=[
{q:'Movie pertama kita tengok sama-sama depan-depan?',a:['Papa Zola','Spider-Man','Upin & Ipin','Avengers'],correct:0},
{q:'First date kita as someone special dekat mana?',a:['Cafe yang Sayang suggest','i-City Mall','Quayside Mall','Cinema'],correct:0},
{q:'Second date kita pergi mana?',a:['i-City Mall','Quayside Mall','Cafe','KLCC'],correct:0},
{q:'Third date kita pergi mana?',a:['Quayside Mall','i-City Mall','Cafe','Sunway Pyramid'],correct:0},
{q:'Fourth date kita tengok movie apa?',a:['Spider-Man','Papa Zola','Batman','Superman'],correct:0},
{q:'Apa nama patung gajah yang Baby surprise untuk Sayang?',a:['Caja','Caya','Caca','Jaja'],correct:0},
{q:'Kenapa Baby bagi surprise Caja?',a:['Sebab Sayang teringin sangat-sangat','Sebab birthday','Sebab menang game','Sebab anniversary'],correct:0},
{q:'Lagu yang bermakna untuk kita?',a:['Kita Usahakan Lagi — Batas Senja','Sempurna','Penjaga Hati','Bergema Sampai Selamanya'],correct:0},
{q:'Kenapa lagu Kita Usahakan Lagi bermakna?',a:['Sebab kita nak usaha sama-sama','Sebab lagu pertama di radio','Sebab Caja suka lagu tu','Sebab lagu birthday'],correct:0},
{q:'Baby nampak Sayang sebagai siapa untuk masa depan?',a:['Orang yang Baby nak kahwin dan bina family dengan','Kawan main game','Partner assignment','Kawan movie'],correct:0}
];
let quizLock=false;
function quizState(){return currentRoom?.game_state||{}}
function shuffledQuestion(i){const base=LOVE_QUIZ_QUESTIONS[i%LOVE_QUIZ_QUESTIONS.length];const items=base.a.map((text,n)=>({text,ok:n===base.correct}));for(let j=items.length-1;j>0;j--){const k=(i*7+j*3+1)%(j+1);[items[j],items[k]]=[items[k],items[j]]}return{q:base.q,options:items.map(x=>x.text),correct:items.findIndex(x=>x.ok)}}
async function startLoveQuiz(){if(!currentRoom||!currentRoom.guest_name)return;const first=shuffledQuestion(0);await db.from('arcade_rooms').update({selected_game:'love-quiz',game_state:{phase:'quiz',round:0,total:10,question:first.q,options:first.options,correct:first.correct,host_answer:null,guest_answer:null,host_score:0,guest_score:0,reveal:false,finished:false}}).eq('id',currentRoom.id)}
function showLoveQuiz(r){currentRoom=r;roomPanel?.classList.add('hidden');$('battlePanel')?.classList.add('hidden');$('tttPanel')?.classList.add('hidden');$('quizPanel')?.classList.remove('hidden');$('quizRoomCode').textContent=r.room_code;renderLoveQuiz(r)}
function renderLoveQuiz(r){const s=r.game_state||{};$('quizBabyName').textContent=r.host_name||'Baby';$('quizSayangName').textContent=r.guest_name||'Sayang';$('quizScore').textContent=`${s.host_score||0} — ${s.guest_score||0}`;$('quizProgress').textContent=s.finished?'Final Result ❤️':`Question ${(s.round||0)+1}/${s.total||10}`;$('quizQuestion').textContent=s.finished?'Siapa paling kenal kisah kita? ❤️':s.question||'';const box=$('quizOptions');box.innerHTML='';if(s.finished){const hs=s.host_score||0,gs=s.guest_score||0;$('quizMessage').textContent=hs===gs?'Draw! Dua-dua memang kenal kisah kita ❤️':hs>gs?`${r.host_name||'Baby'} wins! Tapi dua-dua tetap satu team ❤️`:`${r.guest_name||'Sayang'} wins! Tapi dua-dua tetap satu team ❤️`;$('quizRematchBtn').classList.remove('hidden');return}$('quizRematchBtn').classList.add('hidden');const mine=isHost?s.host_answer:s.guest_answer;$('quizMessage').textContent=s.reveal?`Jawapan: ${s.options?.[s.correct]||''} ❤️`:mine!==null&&mine!==undefined?'Jawapan locked. Tunggu your person ❤️':'Pilih jawapan you ❤️';(s.options||[]).forEach((txt,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=txt;if(mine!==null&&mine!==undefined)b.disabled=true;if(s.reveal&&i===s.correct)b.classList.add('correct');if(s.reveal&&mine===i&&i!==s.correct)b.classList.add('wrong');b.onclick=()=>answerLoveQuiz(i);box.appendChild(b)});if(s.reveal&&!quizLock){quizLock=true;setTimeout(()=>advanceLoveQuiz(),1800)}}
async function answerLoveQuiz(i){if(!currentRoom)return;const s=quizState();if(s.reveal||s.finished)return;const key=isHost?'host_answer':'guest_answer';if(s[key]!==null&&s[key]!==undefined)return;const ns={...s,[key]:i};const other=isHost?ns.guest_answer:ns.host_answer;if(other!==null&&other!==undefined){ns.reveal=true;if(ns.host_answer===ns.correct)ns.host_score=(ns.host_score||0)+1;if(ns.guest_answer===ns.correct)ns.guest_score=(ns.guest_score||0)+1}await db.from('arcade_rooms').update({game_state:ns}).eq('id',currentRoom.id)}
async function advanceLoveQuiz(){if(!currentRoom){quizLock=false;return}const s=quizState();if(!s.reveal){quizLock=false;return}const next=(s.round||0)+1;if(next>=10){await db.from('arcade_rooms').update({game_state:{...s,finished:true,reveal:false}}).eq('id',currentRoom.id);quizLock=false;return}const q=shuffledQuestion(next);await db.from('arcade_rooms').update({game_state:{...s,round:next,question:q.q,options:q.options,correct:q.correct,host_answer:null,guest_answer:null,reveal:false}}).eq('id',currentRoom.id);quizLock=false}
async function exitLoveQuiz(){if(!currentRoom)return;await db.from('arcade_rooms').update({selected_game:null,game_state:{}}).eq('id',currentRoom.id);$('quizPanel')?.classList.add('hidden');roomPanel?.classList.remove('hidden')}
